server:
  port: 8000



spring:
  application:
    name: coursera
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update
  flyway:
    url: ${spring.datasource.jdbcUrl}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}
    baseline-on-migrate: true
    enabled: true
    locations: classpath:/db/migration
  datasource:
    jdbcUrl: jdbc:postgresql://${PG_HOST:localhost}:${PG_PORT:5432}/${PG_DATABASE:coursera}?ApplicationName=${spring.application.name}
    username: ${PG_USERNAME:coursera}
    password: ${PG_PASSWORD:coursera}
    driver-class-name: org.postgresql.Driver

  mail:
    host: smtp.example.com
    port: 587
    username: esbolkuandik@gmail.com
    password: fcibtxveoovxhoye
    properties:
      mail:
        smtp:
          ssl: true
          starttls:
            required: true
            enable: true
          auth: true
        transport:
          protocol: smtp
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 20MB

logging:
  level:
    root: INFO
    dev.langchain4j: DEBUG
    dev.ai4j.openai4j: DEBUG


application:
  authentication:
    jwt:
      secret: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      base64-secret: "sayNC7K8G05C4tal73vbx8Sf0LK13zeK"
      token-validity-in-seconds: 604800000
      token-validity-in-seconds-for-remember-me: 604800000
  cors:
    allowed-origins-base: "http://localhost:5173/"

minio:
  url: http://localhost:9000
  access:
    key: minio
  secret:
    key: minio123
  bucket:
    name: cousera
  file-size: 1073741824

